### ISSUE TITLE
[Exp] Implement Wandb Techniques

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/Total-Knee-Replacement-Post-Surgical-Assessment#31]
## What
Automation tool for experimenting hyperparameters & Save images

## Why
Time is money. Save time.

## TODO
- [x] Implement Wandb Sweep
- [x] Implement Wandb Visualization

**Comment by yehyunsuh** [comment]
https://docs.wandb.ai/guides/sweeps
https://www.youtube.com/watch?v=WZvG6hwxUEw
- Example Code
```yaml
command:
  - python3
  - main.py
  - "--pixel_loss" 
  - "--angle_loss" 
  - "--progressive_erosion"
  - "--progressive_weight" 
  - "--pretrained" 
  - "--wandb" 
  - "--wandb_sweep"
  - "--no_image_save" 
  - "--dilate"
  - "68"
  - "--dilation_decrease" 
  - "2" 
  - "--dilation_epoch" 
  - "10" 
  - "--epochs" 
  - "340" 
  - "--output_channel" 
  - "6"
  - "--angle_loss_weight" 
  - "1000" 
  - "--decoder_channel" 
  - "[512,256,128,64,32]"
  - "--wandb_name"
  - "Sweep_Label6_D68-2_to2_AW-P1000+A_every10_chx2"

method: bayes
project: joint-replacement
entity: yehyun-suh
metric:
  name: Best Angle Difference 
  goal: minimize
parameters:
  learning_rate:
    distribution: uniform
    min: 5e-5
    max: 5e-4
  angle_loss_weight:
    distribution: int_uniform
    min: 750
    max: 1250
  batch_size:
    distribution: int_uniform
    min: 12
    max: 34
  decoder_channel:
    values:
      - [256,128,64,32,16]
      - [384,192,96,48,24]
      - [512,256,128,64,32]
```
- How to create an agent
```shell
wandb sweep sweep.yaml
```
